6.Django/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

6.Django/blog/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:pk>',views.article,name='get_article'),
    path('author/<int:pk>',views.author,name='get_author'),
    path('article',views.create_article,name="create_article"),
]

6.Django/blog/main/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=256) 
    content = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True)
    authors = models.ManyToManyField('Author')

    def __str__(self):
        return self.title

6.Django/blog/main/views.py
from django.db.models.base import Model
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render
from . import models
# Create your views here.


def index(request):
    # Getting first 10 Articles from Articles
    latest_articles = models.Article.objects.all().order_by('-createdAt')[:10]
    # This query won't hit the database unless this variable where it is stored in used somewhere so we can say it as a lazy query
    # print(latest_articles)
    context = {
        'latest_articles': latest_articles
    }
    return render(request, 'main/index.html', context)


def article(request, pk):
    # try:
    #     article = models.Article.objects.get(pk=pk)
    # except:
    #     raise Http404

    article = get_object_or_404(models.Article.objects, pk=pk)

    context = {
        'article': article
    }

    return render(request, 'main/article.html', context)


def author(request, pk):

    author = get_object_or_404(models.Author.objects, pk=pk)

    context = {
        'author': author,
    }

    return render(request, 'main/author.html', context)

def create_article(request):
    print(request.POST)
    authors = models.Author.objects.all()
    context = {
        'authors':authors
    }
    if request.method == 'POST':
        article_data = {
            'title':request.POST['title'],
            'content':request.POST['content'],
        }
        article = models.Article.objects.create(**article_data)
        author = models.Author.objects.get(pk=request.POST['author'])
        article.authors.set([author])
        context['success'] = True
 
    return render(request,'main/create_article.html',context)

6.Django/blog/templates/main/article.html
{% extends 'main/base.html' %}

{% block content %}

<h1>{{article.title}}</h1>
<h3>Created At {{article.createdAt}}</h3>
<h4>Written By :
  {% for author in article.authors.all %} 
    <a href="{% url 'get_author' author.id %}" >{{author}},</a>
  {% endfor %}

</h4>

<p>
  {{article.content}}
</p>
{% endblock %}

6.Django/blog/templates/main/author.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Author Name : {{author.name}}</h1>

<h4>Articles Written :</h4>
<ul>
  {% for article in author.article_set.all%}
  <li>
    <a href="{% url 'get_article' article.id %}">{{article}}</a>
  </li>
  {% endfor %}
</ul>


{% endblock %}

6.Django/blog/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog Application</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
  {% block content %} {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>
</html>

6.Django/blog/templates/main/create_article.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Create New Article : </h1>

{% if success %}
<p>Form Submitted Successfully</p>
{% endif %}

<form method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="title">Title</label>
    <input name="title" type="text" class="form-control" placeholder="Enter tutle">
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <textarea name="content" type="text" class="form-control" id="exampleInputPassword1" placeholder="Password"></textarea>
  </div>
  <div class="form-group">
    <select name="author">
      {% for author in authors %}
      <option value="{{author.id}}">{{author.name}}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="submit" class="btn btn-primary">Reset</button>
  </div>
</form>

{% endblock %}

6.Django/blog/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Welcome to Blog Application. </h1>
<h5>Top 10 Articles</h5>

<ul>
  {% for article in latest_articles%}
  <li>
    <a href="{% url 'get_article' article.id %}">{{article}}</a>
  </li>
  {% endfor %}
</ul>


{% endblock %}