6.Django/polling_application/auth/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('login/',views.Login.as_view(),name='auth_login'),
    path('logout/',views.Logout.as_view(),name='auth_logout'),
]

6.Django/polling_application/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('',views.Index.as_view(),name='index'),
    # path('question/<int:pk>',views.Question.as_view(),name='question'),
    path('question/<slug>',login_required(views.Question.as_view()),name='question'),
]

6.Django/polling_application/poler/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('auth.urls')),
    path('',include('main.urls')),
]

6.Django/polling_application/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import query
# Create your models here.
class Question(models.Model):
    slug = models.SlugField()
    content = models.CharField(max_length=1024)

    def __str__(self):
        return self.content

class Answer(models.Model):
    question = models.ForeignKey('Question',on_delete=models.CASCADE)
    choice  =models.ForeignKey('Choice',on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.question

class Choice(models.Model):
    question = models.ForeignKey('Question',on_delete=models.CASCADE)
    content = models.CharField(max_length=523)

    def answer_count(self):
        return Answer.objects.filter(
            question = self.question,
            choice = self.id
        ).count()


    def __str__(self):
        return "{} - {}".format(self.question.content,self.content)

6.Django/polling_application/main/forms.py
from django import forms
from django.forms import fields
from .models import Answer

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['choice']

6.Django/polling_application/main/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView,DetailView,FormView
from .models import Answer, Question,Choice
from django.views.generic.detail import SingleObjectMixin
from .forms import AnswerForm
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.

class Index(ListView):
    model = Question
    template_name = 'main/index.html'
    # Default context object name is smallm model name _ list i.e. question_list 
    
class Question(PermissionRequiredMixin,FormView,SingleObjectMixin):
    model = Question
    template_name = 'main/question.html'
    form_class = AnswerForm
    permission_required = ['add_answer']

    def form_valid(self, form):
        # Save in memory but not commit in database
        obj = form.save(commit = False)
        # Adding particular field in memory
        obj.question = self.get_object()
        obj.user = self.request.user
        # Commit in database
        obj.save()
        return HttpResponseRedirect('/')

    # Overriding Context data
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        try:
            data['answer'] = Answer.objects.get(
                question = self.get_object(),
                user = self.request.user
            )
        except:
            data['answer'] = None
        return data


    def post(self, request, *args, **kwargs):
        self.object =self.get_object()
        return super().post(self,request,*args,**kwargs)
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object = self.object)
        return self.render_to_response(context)

6.Django/polling_application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Poller Application</title>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

6.Django/polling_application/templates/main/components/navbar.html
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">Poller</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li>
      {% if request.user.is_authenticated   %}
      <a href="{% url 'auth_logout' %}">Logout</a>
      {% else %}
      <a href="{% url 'auth_login' %}">Login</a>

      {% endif %}
    </li>
      <li><a href="#">Leaderboards</a></li>
    </ul>
  </div>
</nav>
      

6.Django/polling_application/templates/main/index.html
{% extends 'base.html' %}

{% block content %}

{% include 'main/components/navbar.html'%}

<div class="container">
  <div class="row">
    <span class="collection-header">
      <h4>Popular Questions </h4>
    </span>
  </div>
 
  <div class="row">
    <div class="col-6">
      <div class="collection">
        {% for question in question_list %}
        <a href="{% url 'question' question.slug %}" class="collection-item">{{question.content}}</a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

6.Django/polling_application/templates/main/question.html
{% extends 'base.html' %}

{% block content %}

{% include 'main/components/navbar.html'%}

<div class="container">
  <div class="row">
    <span class="collection-header">
      <h4>{{question.content}}</h4>
    </span>
  </div>
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-6">
        {% for choice in question.choice_set.all %}
          <div class="collection">
            {% if answer %}
              {{choice.content}} ({{choice.answer_count}})
              {% if answer.choice.id == choice.id %}
              <i class="material-icons right">check</i>
              {% endif %}
            {% else  %}
            <label>
              <input class="with-gap" name="choice" type="radio" value="{{choice.id}}"  />
              <span>{{choice.content}}</span>
            </label>
            {% endif %}
          </div>
          {% endfor %}
      </div>
    </div>
    {% if not answer %}
    <div class="row">
      <button class="btn waves-effect waves-light" type="submit" name="action">
        Submit
        <i class="material-icons right">send</i>
      </button>
    </div>
    {% endif %}

    <div class="row">
      <p class="red">
        <ul>
          {%  for error in form.errors %}
          <li>
            {{error}}
          </li>
          {% endfor %}
        </ul>
      </p>
    </div>
  </form>
</div>

{% endblock %}