6.Django/generic_views/main/urls.py
from django.urls import path
from . import views

# as_view convert class based views into function based view
urlpatterns = [
    path('',views.Index.as_view(),name='index'),
    path('college/<int:pk>',views.CollegeDetail.as_view(),name='college_detail'),
    path('college',views.CollegeList.as_view(),name='college_list'),
    path('create_college',views.CollegeCreate.as_view(),name='create_college'),
    path('update_college/<int:pk>',views.CollegeUpdate.as_view(),name='update_college'),
    path('delete_college/<int:pk>',views.CollegeDelete.as_view(),name='delete_college'),
    path('create_student',views.StudentCreate.as_view(),name='create_student'),
]

6.Django/generic_views/student_management/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

6.Django/generic_views/main/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=255)
    roll_number = models.IntegerField(unique=True)
    college = models.ForeignKey('College',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class College(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

6.Django/generic_views/main/views.py
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import (DetailView,ListView,CreateView,UpdateView,DeleteView)
from .models import Student,College

# Create your views here.
class Index(View):
    def get(request,self):
        return HttpResponse("GET Request")
    
    def post(request,self):
        return HttpResponse("POST Request") 

# Detail View
class CollegeDetail(DetailView):
    model = College
    template_name = 'main/college_detail.html'

# List View
class CollegeList(ListView):
    model = College
    template_name = 'main/college_list.html'
    # Instead of Object we can change its name to anything we want
    context_object_name = 'colleges'

# Create View

class CollegeCreate(CreateView):
    model = College
    template_name = 'main/college_create.html'
    fields = "__all__"
    success_url = '/college'

class StudentCreate(CreateView):
    model = Student
    template_name = 'main/student_create.html'
    fields = "__all__"
    success_url = '/college'

# Update View

class CollegeUpdate(UpdateView):
    model = College
    template_name = 'main/college_create.html'
    fields = "__all__"
    success_url = '/college'

class CollegeDelete(DeleteView):
    model = College
    template_name = 'main/confirm.html'
    fields = "__all__"
    success_url = '/college'



# Delete View

6.Django/generic_views/templates/main/college_create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Create College : </h1>
  <form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Submit</button>
  </form>
</body>
</html>

6.Django/generic_views/templates/main/college_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <!-- Class based view can be accessed directly using object. -->
  <h1>College Name : {{object.name}} </h1>
  <h2>Students : </h2>
  <ul>
    {% for student in object.student_set.all %}
      <li>{{student}}</li>
    {% endfor %}
  </ul>
</body>
</html>

6.Django/generic_views/templates/main/college_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Colleges</h1>
  <ul>
    {% for college in colleges %}
    <li><a href="{% url 'college_detail' college.pk %}">{{college.name}}</a></li>
    {% endfor %}
  </ul>
</body>
</html>

6.Django/generic_views/templates/main/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
  <form method="POST">
    {% csrf_token %}
    {{form}}
    <label for="">Are you sure you want to delete ? </label>
    <button >No</button>
    <button type="submit">Yes</button>
  </form>
</body>
</html>

6.Django/generic_views/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Student Management</h1>
</body>
</html>

6.Django/generic_views/templates/main/student_create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Create Student :</h1>

  <form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Submit</button>
  </form>
</body>
</html>