6.Django/social_media/auth/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('signup',views.Signup.as_view(),name='signup')
]

6.Django/social_media/foxy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('', include('social.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

6.Django/social_media/social/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/',views.Home.as_view(),name='home'),
    path('post/',views.AllPost.as_view(),name='post'),
    path('post/<int:pk>/like/',views.LikePost.as_view(),name='like_post'),
    path('post/<int:pk>/comment/',views.CommentPost.as_view(),name='comment_post'),
    path('',views.Wall.as_view(),name='wall'),
]

6.Django/social_media/social/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    content = models.TextField()
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.content[:50]

class Like(models.Model):
    post = models.ForeignKey('Post',on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey('Post',on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

class Friends(models.Model):
    person1 = models.ForeignKey(User,on_delete=models.CASCADE,related_name='person1')
    person2 = models.ForeignKey(User,on_delete=models.CASCADE,related_name='person2')

6.Django/social_media/social/forms.py
from django import forms
from django.forms import fields
from .models import Post,Comment

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content','image']

class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

6.Django/social_media/social/views.py
from django.forms import fields
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Like, Post
from django.db.models import Q
from .forms import CreatePostForm,PostCommentForm
# Create your views here.


class Wall(LoginRequiredMixin, ListView):
    context_object_name = 'posts'
    template_name = 'social/wall.html'
    login_url = 'auth/login'
    

    def get_queryset(self):
        return Post.objects.filter(
            # search if either person1 is friend of current user or person2 is.and filter post by friend and remove own posts
            (Q(user__person1=self.request.user.pk) | Q(
                user__person2=self.request.user.pk)) & ~Q(user=self.request.user)
        ).order_by('-created_at')


class Home(LoginRequiredMixin, ListView):
    context_object_name = 'posts'
    template_name = 'social/home.html'
    login_url = 'auth/login'

    def get_queryset(self):
        return Post.objects.filter(Q(user=self.request.user)).order_by('-created_at')

    def get_context_data(self, *args, **kwargs):
        # It uses parent class as context data
        data = super().get_context_data(*args, **kwargs)
        # Passing posts data with addition to post_form
        data['post_form'] = CreatePostForm()
        return data


class AllPost(View):
    def post(self, request):
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('/home/')


class LikePost(View):
    model = Post
    def post(self, request, pk):
        post = self.model.objects.get(pk=pk)
        Like.objects.create(post=post, user=request.user)
        return HttpResponse(code=204)

class CommentPost(View):
    model = Post
    form = PostCommentForm

    def post(self, request, pk):
        post = self.model.objects.get(pk=pk)
        form = self.form(request.POST)

        if form.is_valid():
            comment =form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return HttpResponse(code=204)
        return HttpResponse(code=400)

6.Django/social_media/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Foxy</title>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  {% block head %} {% endblock %}

</head>

<body>
  {% include 'navbar.html' %}
  {% block content %} {% endblock %}
  {% block footer %} {% endblock %}
  <!-- Compiled and minified JavaScript -->
  <script src="{% static 'social/social.js' %}"></script>"
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.modal');
      var instances = M.Modal.init(elems, {})
    })
  </script>
</body>

</html>

6.Django/social_media/templates/navbar.html
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Foxy</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      {% if user.is_authenticated %}
      <li><a href="/home">Hello , {{user.first_name}} {{user.last_name}}</a></li>
      <li><a href="/auth/logout">Logout</a></li>
      {% else %}
      <li><a href="/auth/login">Login</a></li>
      <li><a href="/auth/signup">Signup</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

6.Django/social_media/templates/social/components/post.html
<div class="card">
  <div class="card-image">
    {% if post.image %}
    <img src="/media/{{post.image}}" style="width: 25%;">
    {% endif %}
  </div> 
  <div class="card-content">
    <span class="card-title">{{post.user.first_name}} {{post.user.last_name}}</span>
    <p>{{post.content}}.</p>
    <span >{{post.created_at}}</span>
  </div>
  <div class="card-action">
    <a href="#" onclick="likePost({{post.id}});">{{post.like_set.count}} Like</a>
    <a class="modal-trigger" href="#postModal{{post.id}}">{{post.comment_set.count}} Comment </a>
  </div>
</div>

<div id="postModal{{post.id}}" class="modal" >
  <div class="modal-content">
    <h4 style="text-align: center; font-weight: bold;">Comments</h4>
    <ul>
      {% for comment in post.comment_set.all %}
        <li>{{comment.user.first_name}} - {{comment.content}}</li>
      {% endfor %}
    </ul>
    <form class="input-field" onsubmit="commentPost({{post.id}},document.getElementById('comment{{post.id}}').value);">
      <input placeholder="Add Comments" id="comment{{post.id}}" type="text" class="validate">
      <label for="comment{{post.id}}">Comment</label>
      <button type="submit" class="btn waves-effect">Submit</button>
    </form>
  </div>
</div>

6.Django/social_media/templates/social/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3>Home</h3>
    <form action="/post/" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{post_form}}
      <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
      </button>
    </form>
    {% for post in posts %}
    <div class="row">
      {% include 'social/components/post.html' %}
    </div>
    {% endfor %}
  </div>

{% endblock %}

6.Django/social_media/templates/social/wall.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h3>Wall</h3>
  {% for post in posts %}
  <div class="row">
    {% include 'social/components/post.html' %}
  </div>
  {% endfor %}
</div>


{% endblock %}